use std::error::Error;

fn main() -> Result<(), Box<dyn Error>> {
    // TODO: more shit also test Tun pls

    Ok(())
}
